services:
  pg:
    image: postgres
    restart: unless-stopped
    container_name: postgres_container
    ports:
      - "5432:5432"
    networks:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

  backend:
    image: node:slim
    container_name: backend
    restart: unless-stopped
    networks:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - pg
    ports:
      - '123:${PORT:-9000}'
    environment:
      PORT: ${PORT:-9000}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    

networks:
  postgres:
    driver: bridge
  

volumes:
  postgres: